name: Compile LaTeX Documents and Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up LaTeX environment
        run: |
          echo "Installing LaTeX dependencies..."
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends make latexmk texlive-luatex texlive-fonts-recommended texlive-fonts-extra texlive-lang-cyrillic texlive-latex-extra
          echo "Updating luaotfload font cache..."
          sudo luaotfload-tool -uf

      - name: Compile LaTeX documents
        run: |
          echo "Running make..."
          make all

      - name: List files in dist directory
        run: ls -l dist

      - name: Modify GitHub Release (on tag)
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/Polozhennia-pro-OSS.pdf
            dist/Polozhennia-pro-SUD.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}